//! Small, Runtime-owned Resolution budget accounting.

use loom_protocol::Resolution;
use serde::{Deserialize, Serialize};

/// A v0 budget dimension enforced before candidate validation begins.
///
/// These limits are Runtime policy, not World semantics. They bound the
/// number of protocol items the Runtime will inspect in one Resolution and do
/// not alter the pinned Timeline version or the meaning of a Capability
/// rejection.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum BudgetDimension {
    /// Serialized input bytes supplied to one root Action.
    ActionPayloadBytes,
    /// Serialized bytes accepted by the durable Ingress boundary.
    IngressPayloadBytes,
    /// Serialized Runtime evidence retained for one Execution Session.
    SessionProvenanceBytes,
    /// Number of Runtime evidence entries retained for one Execution Session.
    SessionProvenanceEntries,
    /// Largest serialized payload in one proposed Event.
    EventPayloadBytes,
    /// Largest serialized payload in one proposed Work item.
    WorkPayloadBytes,
    /// Number of proposed Events in the Resolution.
    Events,
    /// Number of nested World Effects across all proposed Events.
    Effects,
    /// Number of proposed Durable Work mutations.
    WorkMutations,
    /// Number of Work items generated by matching Reactions.
    ReactionSchedules,
    /// Maximum nested subresolution depth observed in one root execution.
    SubresolutionDepth,
    /// Number of subresolution dispatches attempted in one root execution.
    SubresolutionCount,
    /// Number of mediated entropy requests made in one root execution.
    EntropyRequests,
    /// Total bytes returned by mediated entropy requests in one root execution.
    EntropyBytes,
    /// Largest individual mediated entropy request in one root execution.
    EntropyRequestBytes,
    /// Number of mediated semantic queries made in one root execution.
    SemanticQueries,
    /// Number of semantic hits returned in one root execution.
    SemanticResults,
    /// Total deterministic bytes returned by semantic queries.
    SemanticResultBytes,
    /// Largest semantic query depth observed in one root execution.
    SemanticDepth,
    /// Largest semantic filter count observed in one root execution.
    SemanticFilters,
}

impl std::fmt::Display for BudgetDimension {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let name = match self {
            Self::ActionPayloadBytes => "action_payload_bytes",
            Self::IngressPayloadBytes => "ingress_payload_bytes",
            Self::SessionProvenanceBytes => "session_provenance_bytes",
            Self::SessionProvenanceEntries => "session_provenance_entries",
            Self::EventPayloadBytes => "event_payload_bytes",
            Self::WorkPayloadBytes => "work_payload_bytes",
            Self::Events => "events",
            Self::Effects => "effects",
            Self::WorkMutations => "work_mutations",
            Self::ReactionSchedules => "reaction_schedules",
            Self::SubresolutionDepth => "subresolution_depth",
            Self::SubresolutionCount => "subresolution_count",
            Self::EntropyRequests => "entropy_requests",
            Self::EntropyBytes => "entropy_bytes",
            Self::EntropyRequestBytes => "entropy_request_bytes",
            Self::SemanticQueries => "semantic_queries",
            Self::SemanticResults => "semantic_results",
            Self::SemanticResultBytes => "semantic_result_bytes",
            Self::SemanticDepth => "semantic_depth",
            Self::SemanticFilters => "semantic_filters",
        };
        formatter.write_str(name)
    }
}

/// The measured size of one untrusted Resolution.
///
/// `BudgetUsage` is calculated by Runtime before applying any Effect. It is
/// diagnostic execution metadata, not a persisted World value or a Capability
/// input that can be changed after validation starts.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct BudgetUsage {
    action_payload_bytes: usize,
    ingress_payload_bytes: usize,
    session_provenance_bytes: usize,
    event_payload_bytes: usize,
    work_payload_bytes: usize,
    events: usize,
    effects: usize,
    work_mutations: usize,
    reaction_schedules: usize,
    subresolution_depth: usize,
    subresolution_count: usize,
    entropy_requests: usize,
    entropy_bytes: usize,
    entropy_request_bytes: usize,
    semantic_queries: usize,
    semantic_results: usize,
    semantic_result_bytes: usize,
    semantic_depth: usize,
    semantic_filters: usize,
}

impl BudgetUsage {
    /// Counts protocol items in a Resolution without applying its Effects.
    #[must_use]
    pub fn from_resolution(resolution: &Resolution) -> Self {
        let effects = resolution
            .events
            .iter()
            .map(|event| event.effects.len())
            .sum();
        Self {
            action_payload_bytes: 0,
            ingress_payload_bytes: 0,
            session_provenance_bytes: 0,
            event_payload_bytes: resolution
                .events
                .iter()
                .map(|event| {
                    serde_json::to_vec(&event.payload).map_or(usize::MAX, |bytes| bytes.len())
                })
                .max()
                .unwrap_or(0),
            work_payload_bytes: resolution
                .work
                .iter()
                .filter_map(|mutation| match mutation {
                    loom_protocol::WorkMutation::Schedule(work) => {
                        serde_json::to_vec(&work.payload)
                            .ok()
                            .map(|bytes| bytes.len())
                    }
                    loom_protocol::WorkMutation::Cancel(_) => None,
                })
                .max()
                .unwrap_or(0),
            events: resolution.events.len(),
            effects,
            work_mutations: resolution.work.len(),
            reaction_schedules: 0,
            subresolution_depth: 0,
            subresolution_count: 0,
            entropy_requests: 0,
            entropy_bytes: 0,
            entropy_request_bytes: 0,
            semantic_queries: 0,
            semantic_results: 0,
            semantic_result_bytes: 0,
            semantic_depth: 0,
            semantic_filters: 0,
        }
    }

    /// Returns the number of proposed Events.
    #[must_use]
    pub const fn events(self) -> usize {
        self.events
    }

    /// Returns the largest serialized Event payload observed.
    #[must_use]
    pub const fn event_payload_bytes(self) -> usize {
        self.event_payload_bytes
    }

    /// Returns the largest serialized Work payload observed.
    #[must_use]
    pub const fn work_payload_bytes(self) -> usize {
        self.work_payload_bytes
    }

    /// Returns the number of nested Effects.
    #[must_use]
    pub const fn effects(self) -> usize {
        self.effects
    }

    /// Returns the number of Work mutations.
    #[must_use]
    pub const fn work_mutations(self) -> usize {
        self.work_mutations
    }

    /// Returns the number of generated Reaction Work items observed.
    #[must_use]
    pub const fn reaction_schedules(self) -> usize {
        self.reaction_schedules
    }

    /// Returns the deepest nested subresolution observed so far.
    #[must_use]
    pub const fn subresolution_depth(self) -> usize {
        self.subresolution_depth
    }

    /// Returns the number of subresolution dispatches attempted so far.
    #[must_use]
    pub const fn subresolution_count(self) -> usize {
        self.subresolution_count
    }

    /// Returns the number of mediated entropy requests observed so far.
    #[must_use]
    pub const fn entropy_requests(self) -> usize {
        self.entropy_requests
    }

    /// Returns the total number of mediated entropy bytes observed so far.
    #[must_use]
    pub const fn entropy_bytes(self) -> usize {
        self.entropy_bytes
    }

    /// Returns the largest individual entropy request observed so far.
    #[must_use]
    pub const fn entropy_request_bytes(self) -> usize {
        self.entropy_request_bytes
    }

    /// Returns the number of mediated semantic queries observed so far.
    #[must_use]
    pub const fn semantic_queries(self) -> usize {
        self.semantic_queries
    }

    /// Returns the number of semantic hits observed so far.
    #[must_use]
    pub const fn semantic_results(self) -> usize {
        self.semantic_results
    }

    /// Returns the total deterministic semantic result bytes observed so far.
    #[must_use]
    pub const fn semantic_result_bytes(self) -> usize {
        self.semantic_result_bytes
    }

    pub(crate) fn combine(self, other: Self) -> Self {
        Self {
            action_payload_bytes: self.action_payload_bytes.max(other.action_payload_bytes),
            ingress_payload_bytes: self.ingress_payload_bytes.max(other.ingress_payload_bytes),
            session_provenance_bytes: self
                .session_provenance_bytes
                .max(other.session_provenance_bytes),
            event_payload_bytes: self.event_payload_bytes.max(other.event_payload_bytes),
            work_payload_bytes: self.work_payload_bytes.max(other.work_payload_bytes),
            events: self.events.saturating_add(other.events),
            effects: self.effects.saturating_add(other.effects),
            work_mutations: self.work_mutations.saturating_add(other.work_mutations),
            reaction_schedules: self
                .reaction_schedules
                .saturating_add(other.reaction_schedules),
            subresolution_depth: self.subresolution_depth.max(other.subresolution_depth),
            subresolution_count: self
                .subresolution_count
                .saturating_add(other.subresolution_count),
            entropy_requests: self.entropy_requests.saturating_add(other.entropy_requests),
            entropy_bytes: self.entropy_bytes.saturating_add(other.entropy_bytes),
            entropy_request_bytes: self.entropy_request_bytes.max(other.entropy_request_bytes),
            semantic_queries: self.semantic_queries.saturating_add(other.semantic_queries),
            semantic_results: self.semantic_results.saturating_add(other.semantic_results),
            semantic_result_bytes: self
                .semantic_result_bytes
                .saturating_add(other.semantic_result_bytes),
            semantic_depth: self.semantic_depth.max(other.semantic_depth),
            semantic_filters: self.semantic_filters.max(other.semantic_filters),
        }
    }

    pub(crate) const fn with_reaction_schedules(self, schedules: usize) -> Self {
        Self {
            reaction_schedules: self.reaction_schedules.saturating_add(schedules),
            ..self
        }
    }

    pub(crate) const fn with_subresolution(self, depth: usize, count: usize) -> Self {
        Self {
            subresolution_depth: depth,
            subresolution_count: count,
            ..self
        }
    }

    pub(crate) const fn with_entropy(self, request_bytes: usize) -> Self {
        let entropy_request_bytes = if self.entropy_request_bytes > request_bytes {
            self.entropy_request_bytes
        } else {
            request_bytes
        };
        Self {
            entropy_requests: self.entropy_requests.saturating_add(1),
            entropy_bytes: self.entropy_bytes.saturating_add(request_bytes),
            entropy_request_bytes,
            ..self
        }
    }

    pub(crate) fn with_semantic_request(self, depth: usize, filters: usize) -> Self {
        Self {
            semantic_queries: self.semantic_queries.saturating_add(1),
            semantic_depth: self.semantic_depth.max(depth),
            semantic_filters: self.semantic_filters.max(filters),
            ..self
        }
    }

    pub(crate) fn with_semantic_result(self, results: usize, bytes: usize) -> Self {
        Self {
            semantic_results: self.semantic_results.saturating_add(results),
            semantic_result_bytes: self.semantic_result_bytes.saturating_add(bytes),
            ..self
        }
    }
}

/// A Runtime policy limiting the amount of protocol data one Resolution may
/// ask the Effect Engine to inspect.
///
/// `None` means that a dimension is not limited by this policy. The explicit
/// [`ResolutionBudget::unlimited`] constructor is reserved for tests and
/// trusted callers that intentionally opt out; [`Default`] is finite so a
/// production Runtime never starts with an unbounded recursive path. A budget
/// failure is a Runtime validation error and is distinct from
/// `loom_protocol::Rejection`.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(default)]
pub struct ResolutionBudget {
    action_payload_bytes: Option<usize>,
    ingress_payload_bytes: Option<usize>,
    session_provenance_bytes: Option<usize>,
    session_provenance_entries: Option<usize>,
    event_payload_bytes: Option<usize>,
    work_payload_bytes: Option<usize>,
    events: Option<usize>,
    effects: Option<usize>,
    work_mutations: Option<usize>,
    reaction_schedules: Option<usize>,
    subresolution_depth: Option<usize>,
    subresolution_count: Option<usize>,
    entropy_requests: Option<usize>,
    entropy_bytes: Option<usize>,
    entropy_request_bytes: Option<usize>,
    semantic_queries: Option<usize>,
    semantic_results: Option<usize>,
    semantic_result_bytes: Option<usize>,
    semantic_depth: Option<usize>,
    semantic_filters: Option<usize>,
}

impl ResolutionBudget {
    /// Creates a budget from optional limits for the v0 dimensions.
    #[must_use]
    pub const fn new(
        max_events: Option<usize>,
        max_effects: Option<usize>,
        max_work_mutations: Option<usize>,
    ) -> Self {
        Self {
            action_payload_bytes: None,
            ingress_payload_bytes: None,
            session_provenance_bytes: None,
            session_provenance_entries: None,
            event_payload_bytes: None,
            work_payload_bytes: None,
            events: max_events,
            effects: max_effects,
            work_mutations: max_work_mutations,
            reaction_schedules: None,
            subresolution_depth: None,
            subresolution_count: None,
            entropy_requests: None,
            entropy_bytes: None,
            entropy_request_bytes: None,
            semantic_queries: None,
            semantic_results: None,
            semantic_result_bytes: None,
            semantic_depth: None,
            semantic_filters: None,
        }
    }

    /// Returns a policy with no v0 dimension limits.
    #[must_use]
    pub const fn unlimited() -> Self {
        Self::new(None, None, None)
    }

    /// Creates the finite production-safe default policy.
    #[must_use]
    pub const fn default_policy() -> Self {
        Self {
            action_payload_bytes: Some(256 * 1024),
            ingress_payload_bytes: Some(512 * 1024),
            session_provenance_bytes: Some(4 * 1024 * 1024),
            session_provenance_entries: Some(4_096),
            event_payload_bytes: Some(256 * 1024),
            work_payload_bytes: Some(256 * 1024),
            events: Some(256),
            effects: Some(1_024),
            work_mutations: Some(256),
            reaction_schedules: Some(256),
            subresolution_depth: Some(8),
            subresolution_count: Some(64),
            entropy_requests: Some(128),
            entropy_bytes: Some(256 * 1024),
            entropy_request_bytes: Some(64 * 1024),
            semantic_queries: Some(64),
            semantic_results: Some(1_024),
            semantic_result_bytes: Some(1_048_576),
            semantic_depth: Some(32),
            semantic_filters: Some(1),
        }
    }

    /// Sets the maximum serialized root Action input size.
    #[must_use]
    pub const fn with_max_action_payload_bytes(mut self, limit: usize) -> Self {
        self.action_payload_bytes = Some(limit);
        self
    }

    /// Sets the maximum serialized durable Ingress envelope size.
    #[must_use]
    pub const fn with_max_ingress_payload_bytes(mut self, limit: usize) -> Self {
        self.ingress_payload_bytes = Some(limit);
        self
    }

    /// Sets the maximum serialized evidence retained for one Session.
    #[must_use]
    pub const fn with_max_session_provenance_bytes(mut self, limit: usize) -> Self {
        self.session_provenance_bytes = Some(limit);
        self
    }

    /// Sets the maximum number of evidence entries retained for one Session.
    #[must_use]
    pub const fn with_max_session_provenance_entries(mut self, limit: usize) -> Self {
        self.session_provenance_entries = Some(limit);
        self
    }

    /// Sets the maximum serialized Event payload size.
    #[must_use]
    pub const fn with_max_event_payload_bytes(mut self, limit: usize) -> Self {
        self.event_payload_bytes = Some(limit);
        self
    }

    /// Sets the maximum serialized Work payload size.
    #[must_use]
    pub const fn with_max_work_payload_bytes(mut self, limit: usize) -> Self {
        self.work_payload_bytes = Some(limit);
        self
    }

    /// Sets the maximum Reaction-generated Work fan-out per root execution.
    #[must_use]
    pub const fn with_max_reaction_schedules(mut self, limit: usize) -> Self {
        self.reaction_schedules = Some(limit);
        self
    }

    /// Returns the maximum root Action input size.
    #[must_use]
    pub const fn max_action_payload_bytes(self) -> Option<usize> {
        self.action_payload_bytes
    }

    /// Returns the maximum durable Ingress envelope size.
    #[must_use]
    pub const fn max_ingress_payload_bytes(self) -> Option<usize> {
        self.ingress_payload_bytes
    }

    /// Returns the maximum serialized Session evidence size.
    #[must_use]
    pub const fn max_session_provenance_bytes(self) -> Option<usize> {
        self.session_provenance_bytes
    }

    /// Returns the maximum number of evidence entries retained for one
    /// Session.
    #[must_use]
    pub const fn max_session_provenance_entries(self) -> Option<usize> {
        self.session_provenance_entries
    }

    /// Returns the maximum Event payload size.
    #[must_use]
    pub const fn max_event_payload_bytes(self) -> Option<usize> {
        self.event_payload_bytes
    }

    /// Returns the maximum Work payload size.
    #[must_use]
    pub const fn max_work_payload_bytes(self) -> Option<usize> {
        self.work_payload_bytes
    }

    /// Returns the maximum Reaction-generated Work fan-out.
    #[must_use]
    pub const fn max_reaction_schedules(self) -> Option<usize> {
        self.reaction_schedules
    }

    /// Sets the maximum number of Events while preserving other limits.
    #[must_use]
    pub const fn with_max_events(mut self, limit: usize) -> Self {
        self.events = Some(limit);
        self
    }

    /// Sets the maximum number of nested Effects while preserving other
    /// limits.
    #[must_use]
    pub const fn with_max_effects(mut self, limit: usize) -> Self {
        self.effects = Some(limit);
        self
    }

    /// Sets the maximum number of Work mutations while preserving other
    /// limits.
    #[must_use]
    pub const fn with_max_work_mutations(mut self, limit: usize) -> Self {
        self.work_mutations = Some(limit);
        self
    }

    /// Returns the configured Event limit.
    #[must_use]
    pub const fn max_events(self) -> Option<usize> {
        self.events
    }

    /// Returns the configured Effect limit.
    #[must_use]
    pub const fn max_effects(self) -> Option<usize> {
        self.effects
    }

    /// Returns the configured Work mutation limit.
    #[must_use]
    pub const fn max_work_mutations(self) -> Option<usize> {
        self.work_mutations
    }

    /// Sets the maximum nested subresolution depth for one root execution.
    ///
    /// A root Action/Work resolver has depth zero. Its first child
    /// subresolution has depth one. The limit is checked before the child
    /// resolver is dispatched.
    #[must_use]
    pub const fn with_max_subresolution_depth(mut self, limit: usize) -> Self {
        self.subresolution_depth = Some(limit);
        self
    }

    /// Sets the maximum number of subresolution dispatches for one root
    /// execution. A rejected child still consumes one dispatch budget because
    /// it was routed and executed.
    #[must_use]
    pub const fn with_max_subresolution_count(mut self, limit: usize) -> Self {
        self.subresolution_count = Some(limit);
        self
    }

    /// Returns the configured nested subresolution depth limit.
    #[must_use]
    pub const fn max_subresolution_depth(self) -> Option<usize> {
        self.subresolution_depth
    }

    /// Returns the configured subresolution dispatch-count limit.
    #[must_use]
    pub const fn max_subresolution_count(self) -> Option<usize> {
        self.subresolution_count
    }

    /// Sets the maximum number of mediated entropy requests for one root.
    #[must_use]
    pub const fn with_max_entropy_requests(mut self, limit: usize) -> Self {
        self.entropy_requests = Some(limit);
        self
    }

    /// Sets the maximum total mediated entropy bytes for one root.
    #[must_use]
    pub const fn with_max_entropy_bytes(mut self, limit: usize) -> Self {
        self.entropy_bytes = Some(limit);
        self
    }

    /// Sets the maximum bytes permitted in one mediated entropy request.
    #[must_use]
    pub const fn with_max_entropy_request_bytes(mut self, limit: usize) -> Self {
        self.entropy_request_bytes = Some(limit);
        self
    }

    /// Returns the maximum number of mediated entropy requests.
    #[must_use]
    pub const fn max_entropy_requests(self) -> Option<usize> {
        self.entropy_requests
    }

    /// Returns the maximum total mediated entropy bytes.
    #[must_use]
    pub const fn max_entropy_bytes(self) -> Option<usize> {
        self.entropy_bytes
    }

    /// Returns the maximum bytes permitted in one mediated entropy request.
    #[must_use]
    pub const fn max_entropy_request_bytes(self) -> Option<usize> {
        self.entropy_request_bytes
    }

    /// Returns the configured semantic query limit.
    #[must_use]
    pub const fn max_semantic_queries(self) -> Option<usize> {
        self.semantic_queries
    }

    /// Returns the configured semantic hit limit.
    #[must_use]
    pub const fn max_semantic_results(self) -> Option<usize> {
        self.semantic_results
    }

    /// Returns the configured semantic result-byte limit.
    #[must_use]
    pub const fn max_semantic_result_bytes(self) -> Option<usize> {
        self.semantic_result_bytes
    }

    /// Returns the configured semantic depth limit.
    #[must_use]
    pub const fn max_semantic_depth(self) -> Option<usize> {
        self.semantic_depth
    }

    /// Returns the configured semantic filter-count limit.
    #[must_use]
    pub const fn max_semantic_filters(self) -> Option<usize> {
        self.semantic_filters
    }

    /// Sets the maximum semantic queries per root execution.
    #[must_use]
    pub const fn with_max_semantic_queries(mut self, limit: usize) -> Self {
        self.semantic_queries = Some(limit);
        self
    }

    /// Sets the maximum semantic hits per root execution.
    #[must_use]
    pub const fn with_max_semantic_results(mut self, limit: usize) -> Self {
        self.semantic_results = Some(limit);
        self
    }

    /// Sets the maximum semantic result bytes per root execution.
    #[must_use]
    pub const fn with_max_semantic_result_bytes(mut self, limit: usize) -> Self {
        self.semantic_result_bytes = Some(limit);
        self
    }

    /// Sets the maximum semantic query depth per root execution.
    #[must_use]
    pub const fn with_max_semantic_depth(mut self, limit: usize) -> Self {
        self.semantic_depth = Some(limit);
        self
    }

    /// Sets the maximum semantic filter count per query.
    #[must_use]
    pub const fn with_max_semantic_filters(mut self, limit: usize) -> Self {
        self.semantic_filters = Some(limit);
        self
    }

    #[expect(
        clippy::too_many_lines,
        reason = "the check table keeps every policy dimension visible at one boundary"
    )]
    pub(crate) fn check(self, usage: BudgetUsage) -> Result<(), BudgetError> {
        let dimensions = [
            (
                BudgetDimension::ActionPayloadBytes,
                self.action_payload_bytes,
                usage.action_payload_bytes,
            ),
            (
                BudgetDimension::IngressPayloadBytes,
                self.ingress_payload_bytes,
                usage.ingress_payload_bytes,
            ),
            (
                BudgetDimension::SessionProvenanceBytes,
                self.session_provenance_bytes,
                usage.session_provenance_bytes,
            ),
            (
                BudgetDimension::SessionProvenanceEntries,
                self.session_provenance_entries,
                0,
            ),
            (
                BudgetDimension::EventPayloadBytes,
                self.event_payload_bytes,
                usage.event_payload_bytes,
            ),
            (
                BudgetDimension::WorkPayloadBytes,
                self.work_payload_bytes,
                usage.work_payload_bytes,
            ),
            (BudgetDimension::Events, self.events, usage.events),
            (BudgetDimension::Effects, self.effects, usage.effects),
            (
                BudgetDimension::WorkMutations,
                self.work_mutations,
                usage.work_mutations,
            ),
            (
                BudgetDimension::ReactionSchedules,
                self.reaction_schedules,
                usage.reaction_schedules,
            ),
            (
                BudgetDimension::SubresolutionDepth,
                self.subresolution_depth,
                usage.subresolution_depth,
            ),
            (
                BudgetDimension::SubresolutionCount,
                self.subresolution_count,
                usage.subresolution_count,
            ),
            (
                BudgetDimension::EntropyRequests,
                self.entropy_requests,
                usage.entropy_requests,
            ),
            (
                BudgetDimension::EntropyBytes,
                self.entropy_bytes,
                usage.entropy_bytes,
            ),
            (
                BudgetDimension::EntropyRequestBytes,
                self.entropy_request_bytes,
                usage.entropy_request_bytes,
            ),
            (
                BudgetDimension::SemanticQueries,
                self.semantic_queries,
                usage.semantic_queries,
            ),
            (
                BudgetDimension::SemanticResults,
                self.semantic_results,
                usage.semantic_results,
            ),
            (
                BudgetDimension::SemanticResultBytes,
                self.semantic_result_bytes,
                usage.semantic_result_bytes,
            ),
            (
                BudgetDimension::SemanticDepth,
                self.semantic_depth,
                usage.semantic_depth,
            ),
            (
                BudgetDimension::SemanticFilters,
                self.semantic_filters,
                usage.semantic_filters,
            ),
        ];

        for (dimension, limit, actual) in dimensions {
            if let Some(limit) = limit
                && actual > limit
            {
                return Err(BudgetError {
                    dimension,
                    limit,
                    actual,
                });
            }
        }
        Ok(())
    }

    pub(crate) fn check_value(
        self,
        dimension: BudgetDimension,
        actual: usize,
    ) -> Result<(), BudgetError> {
        let limit = match dimension {
            BudgetDimension::ActionPayloadBytes => self.action_payload_bytes,
            BudgetDimension::IngressPayloadBytes => self.ingress_payload_bytes,
            BudgetDimension::SessionProvenanceBytes => self.session_provenance_bytes,
            BudgetDimension::SessionProvenanceEntries => self.session_provenance_entries,
            BudgetDimension::EventPayloadBytes => self.event_payload_bytes,
            BudgetDimension::WorkPayloadBytes => self.work_payload_bytes,
            _ => None,
        };
        if let Some(limit) = limit
            && actual > limit
        {
            return Err(BudgetError {
                dimension,
                limit,
                actual,
            });
        }
        Ok(())
    }
}

impl Default for ResolutionBudget {
    fn default() -> Self {
        Self::default_policy()
    }
}

/// A typed failure raised when a Resolution exceeds a Runtime budget.
///
/// This failure prevents validation from producing a `ValidatedResolution`;
/// it is not a Capability semantic rejection and must remain on the Runtime
/// error path.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct BudgetError {
    /// Dimension whose configured limit was exceeded.
    pub dimension: BudgetDimension,
    /// Configured maximum for the dimension.
    pub limit: usize,
    /// Measured Resolution usage.
    pub actual: usize,
}

impl std::fmt::Display for BudgetError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            formatter,
            "resolution {} budget exceeded: {} > {}",
            self.dimension, self.actual, self.limit
        )
    }
}

impl std::error::Error for BudgetError {}

/// Runtime-owned bounds for history and causal traversal reads.
///
/// These values bound materialization before a query reaches the persistence
/// adapter. They are policy, not Core semantics; a cursor remains the only
/// supported way to continue a larger history read.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(default)]
pub struct HistoryBudget {
    query_page_size: u32,
    causal_depth: u32,
    causal_results: u32,
    change_feed_page_size: u32,
}

impl HistoryBudget {
    /// Creates explicit finite history and causal traversal bounds.
    #[must_use]
    pub const fn new(
        max_query_page_size: u32,
        max_causal_depth: u32,
        max_causal_results: u32,
    ) -> Self {
        Self {
            query_page_size: max_query_page_size,
            causal_depth: max_causal_depth,
            causal_results: max_causal_results,
            change_feed_page_size: 256,
        }
    }

    /// Returns the maximum history page size.
    #[must_use]
    pub const fn max_query_page_size(self) -> u32 {
        self.query_page_size
    }

    /// Returns the maximum causal walk depth.
    #[must_use]
    pub const fn max_causal_depth(self) -> u32 {
        self.causal_depth
    }

    /// Returns the maximum causal walk result count.
    #[must_use]
    pub const fn max_causal_results(self) -> u32 {
        self.causal_results
    }

    /// Returns the Runtime operational Change Feed page bound.
    #[must_use]
    pub const fn max_change_feed_page_size(self) -> u32 {
        self.change_feed_page_size
    }

    /// Sets the Runtime operational Change Feed page bound.
    #[must_use]
    pub const fn with_max_change_feed_page_size(mut self, limit: u32) -> Self {
        self.change_feed_page_size = limit;
        self
    }
}

impl Default for HistoryBudget {
    fn default() -> Self {
        Self::new(1_024, 64, 1_024)
    }
}
